[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:granian]
command=/app/.venv/bin/granian --interface asgi --host 0.0.0.0 --port 8000 --workers %(ENV_GRANIAN_WORKERS)s simple_commerce_backend.asgi:application
directory=/app
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/granian.out.log
stderr_logfile=/var/log/supervisor/granian.err.log
environment=DJANGO_SETTINGS_MODULE="simple_commerce_backend.settings"
